baseurl = "https://eagleviewmedia.com/"
languageCode = "en-us"
title = "The Talon"
# Define how many pages appear per site
paginate = 1
copyright = "The Eagleview Talon.  All rights reserved."
theme = "hugo-zen"


[params]
  logo      = "/images/talon_logo.jpg"

